services:
  frontend:
    build:
      context: ../smartlogix-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - bff

  bff:
    build:
      context: ../smartlogix-bff
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - inventario-ms
      - pedidos-ms

  mysql:
    image: mysql:8.0
    container_name: smartlogix-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smartlogix_inventario
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -proot || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d

  inventario-ms:
    build:
      context: ../smartlogix-inventario-ms
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy

  pedidos-ms:
    build:
      context: ../smartlogix-pedidos-ms
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: